# Numerical Python(Numpy)

In [8]:
import numpy as np # 표준
a = [1,2,3]
a * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [9]:
list(map(lambda x: 3 * x , a))

[3, 6, 9]

In [10]:
b = np.array([1,2,3])
b * 3 
# (b * 3).tolist()

array([3, 6, 9])

# 1. Numpy Dimensional array

In [12]:
a = np.array([1,2,5,8], float)
a

array([1., 2., 5., 8.])

In [13]:
type(a)

numpy.ndarray

In [14]:
a.dtype, a.shape

(dtype('float64'), (4,))

# 2.Array shape

In [15]:
# vector(1차원)
vector = np.array([1,4,5,8])
vector.shape

(4,)

In [16]:
# matrix(2차원)
matrix = np.array([[1,2,3], [4,5,6]])
print(matrix.shape)
print(matrix)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [17]:
# Tensor(3차원)
tensor = np.arange(1, 25).reshape(2,3,4)
print(tensor)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [18]:
vector.shape, matrix.shape, tensor.shape

((4,), (2, 3), (2, 3, 4))

In [19]:
vector.size, matrix.size, tensor.size

(4, 6, 24)

In [20]:
a = np.array([1,2,3], dtype=np.float32)

In [22]:
b = np.array([1,2,3], np.int16)

In [23]:
b

array([1, 2, 3], dtype=int16)

배열의 인덱싱

In [2]:
import numpy as np
a = np.array((1,2,3,4,5))
type(a)

numpy.ndarray

In [3]:
a.dtype, a.shape, a.ndim, a.size

(dtype('int32'), (5,), 1, 5)

In [4]:
# 벡터화 연산
a * 2

array([ 2,  4,  6,  8, 10])

In [5]:
b = np.array([10,20,30,40,50])
c = 2 * a + b
print(c)

[12 24 36 48 60]


In [6]:
a == 2

array([False,  True, False, False, False])

In [7]:
b > 20

array([False, False,  True,  True,  True])

2 차원배열(matrix)

In [8]:
c = np.array([[1,2,3], [4,5,6]])
# c = np.arange(1, 7).reshape(2, 3)
c

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
c.dtype, c.shape, c.ndim, c.size

(dtype('int32'), (2, 3), 2, 6)

3차원 배열(Tensor)

In [11]:
d = np.arange(1,25).reshape(2,3,4)
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [12]:
d.dtype, d.shape, d.ndim, d.size

(dtype('int32'), (2, 3, 4), 3, 24)

In [13]:
a[0], a[3], a[-1]

(1, 4, 5)

In [15]:
c[0, 0], c[0][0]

(1, 1)

In [18]:
c[1, 0], c[0, -1], c[-1,-1]

(4, 3, 6)

In [20]:
d[0, -1, 0], d[-1, 1, -1]  # dim, 행, 열

(9, 20)

배열의 슬라이싱

In [22]:
l = [[1,2,3], [4,5,6], [7, 8, 9]]
l[0:2]

[[1, 2, 3], [4, 5, 6]]

In [23]:
l[:2][:2]

[[1, 2, 3], [4, 5, 6]]

In [24]:
l[1][:2]

[4, 5]

In [25]:
c = np.arange(1, 13).reshape(3,4)
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
c[:2] # 두 행 뽑기

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [32]:
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
c[:][-2:] 

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
c[:, -2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [28]:
c[:, 2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [33]:
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
c[:][2:]

array([[ 9, 10, 11, 12]])

In [34]:
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# 1,3,5,7
c[:2, ::2]


In [36]:
# 2,3,6,7
c[0:2, 1:3]

array([[2, 3],
       [6, 7]])

In [37]:
c[:-1, 1:3]

array([[2, 3],
       [6, 7]])

In [41]:
m = np.arange(15).reshape(3,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [45]:
# 1. 7을 인덱싱
print(m[1,2])
#2. 14를 인덱싱 2가지 방법
print(m[-1, -1], m[2, 4])
# 3. [6,7] 슬라이싱
print(m[1, 1:3])
# 4.  [7, 12] 를 슬라이싱
print(m[-2:, 2], m[1:, 2])
# 5. [[3,4], [8, 9]] 를 슬라이싱
print(m[:2, -2:], m[:2, 3:])

7
14 14
[6 7]
[ 7 12] [ 7 12]
[[3 4]
 [8 9]] [[3 4]
 [8 9]]


In [46]:
# 6. 맨 마지막 열이 y, 나머지는 x 가되도록 x와 y를 슬라이싱
X = m[:, :-1]
y = m[:, -1]

배열 인덱싱(Fancy indexing)

In [47]:
# idx  값이 True/ False 이면, True값이 있는 원소만 통과(filter)
print(a)

[1 2 3 4 5]


In [51]:
idx = np.array([True, False, True, True, False])
print(a[idx])

[1 3 4]


In [52]:
# 홀수만 통과
a[a % 2 == 1]

array([1, 3, 5])

In [53]:
# 3보다 큰수만 통과
a[a > 3]

array([4, 5])

In [54]:
# idx 값이 정수(인덱스)면 해당 인덱스의 원소가 선택됨
idx = np.array([1,2,4])
a[idx] # a[1], a[2] , a[4]

array([2, 3, 5])

연습

In [55]:
x = np.arange(1, 21)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
# 1. 3의 배수를 찾으세요
x[x % 3 ==0 ]
# 2. 4로나누면 1이 남는 수를 찾으세요 
x[x % 4 == 1]
# 3. 3으로 나눠지고 4로 나누면 1이 남는 수를 찾으세요  --> 9
x[(x % 3 ==0) & (x % 4 == 1)]
# 4. 3번을 fancy indexing으로 코드를 수정하세요

In [57]:
x[(x % 3 ==0) & (x % 4 == 1)]

array([9])