연습문제

In [1]:
import numpy as np

1.번 정답

In [3]:
np.arange(1,9).reshape(2, 4)*10

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

2번 정답

In [6]:
m = np.arange(15).reshape(3, 5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
#1번 7인덱싱 / 2번 14 인덱싱
m[1,2], m[-1, -1]

(7, 14)

In [9]:
# 3번 [6,7] 슬라이싱
m[1, 1:3]

array([6, 7])

In [11]:
# 4번 [7,12] 슬라이싱
m[1:3, 2], m[1:, 2]

(array([ 7, 12]), array([ 7, 12]))

In [13]:
# 5번 [[3,4], [8,9]]
m[:2, -2:], m[:2, 3:]

(array([[3, 4],
        [8, 9]]),
 array([[3, 4],
        [8, 9]]))

3번

In [15]:
f = m.flatten()
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
# 1번 3의배수
f[f % 3 == 0]

array([ 0,  3,  6,  9, 12])

In [20]:
# 2번 4로 나눠 나머지 1
f[f % 4 == 1]

array([ 1,  5,  9, 13])

In [21]:
# 3번 3로 나눠면 나눠지고 4로 나누면 나머지 1
f[np.logical_and(f%3==0, f%4==1)]

array([9])

4번

In [25]:
np.eye(5,5, k=-1)*3 + np.eye(5,5)*2 + np.eye(5,5, k=1)

array([[2., 1., 0., 0., 0.],
       [3., 2., 1., 0., 0.],
       [0., 3., 2., 1., 0.],
       [0., 0., 3., 2., 1.],
       [0., 0., 0., 3., 2.]])

5번

In [30]:
np.random.seed(2023)
m = np.random.uniform(0,10, 30).reshape(5,6).round(3)
m

array([[3.22 , 8.904, 5.881, 1.266, 1.413, 4.679],
       [0.221, 7.273, 5.244, 5.449, 4.564, 5.014],
       [3.945, 1.512, 3.609, 1.621, 3.38 , 1.803],
       [3.91 , 0.356, 5.649, 2.035, 3.206, 3.766],
       [1.841, 1.04 , 4.549, 1.959, 3.785, 9.305]])

In [32]:
# 1번
m.max(), np.max(m)

(9.305, 9.305)

In [33]:
# 2번
np.sum(m), m.sum()

(110.399, 110.399)

In [36]:
# 2번
np.sum(m, axis=1)

array([25.363, 27.765, 15.87 , 18.922, 22.479])

In [37]:
# 3번
np.max(m, axis=1)

array([8.904, 7.273, 3.945, 5.649, 9.305])

In [39]:
# 4번
np.mean(m, axis=0)

array([2.6274, 3.817 , 4.9864, 2.466 , 3.2696, 4.9134])

In [41]:
# 5번
np.min(m, axis=0)

array([0.221, 0.356, 3.609, 1.266, 1.413, 1.803])

6번

In [42]:
score = np.array([[1, 2, 3, 4], [46, 99, 100, 71], [81, 59,90, 100]])
score

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [43]:
np.sort(score)

array([[  1,   2,   3,   4],
       [ 46,  71,  99, 100],
       [ 59,  81,  90, 100]])

In [47]:
score

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [44]:
s = np.argsort(score[1])
# argsort는 인덱스를 반환하는 함수 score[1]은 첫번째 행을 선택하는 방법
s

array([0, 3, 1, 2])

In [48]:
s[::-1]

array([2, 1, 3, 0])

In [49]:
score[:, s[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [50]:
# 정답을 한줄로
score[:, np.argsort(score[1])[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

7번

In [1]:
# 주사위
import numpy as np
np.random.seed(2023)
dice = np.random.randint(1, 7, 1000)
# dice

In [2]:
np.mean(dice)

3.527

In [3]:
np.unique(dice) # set{} 집합 중복제거 순서에 상관없다
# dice = [1,1,1,1,1,1,2,2,2,2,6]
# 1,6,2

array([1, 2, 3, 4, 5, 6])

8번

In [4]:
# 10개 먼저 테스트
np.random.seed(2023)
price = 10000
rate = np.random.normal(0, 0.01, 10)
for i in range(10):
  price = price + np.round(price*rate[i])
  print(price, end=',')

10071.0,10038.0,9937.0,9960.0,9950.0,9836.0,10097.0,10242.0,10252.0,9932.0,

In [5]:
np.random.seed(2023)
price_list = []
price = 10000
rate = np.random.normal(0, 0.01, 250)
for i in range(250):
  price = price + np.round(price*rate[i])
  price_list.append(price)

In [6]:
price_list[:20]

[10071.0,
 10038.0,
 9937.0,
 9960.0,
 9950.0,
 9836.0,
 10097.0,
 10242.0,
 10252.0,
 9932.0,
 9825.0,
 9793.0,
 9692.0,
 9651.0,
 9552.0,
 9502.0,
 9462.0,
 9453.0,
 9323.0,
 9351.0]